#name, main, version and api are required
name: invclear
main: invclear.Invclear
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: sjimin
description: inventory clear
website: https://github.com/sJimin/Nukkit-Plugins


commands:
 ci:
  permission: ci.commands
  description: inventory clear!
  usage: "/ci"
  default: OP
  
permissions:
 ci.commands:
  default: OP
