#name, main, version and api are required
name: motd
main: motd.Motd
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: sjimin
description: motd , server's name edit plugin
website: https://github.com/sJimin/Nukkit-Plugins


commands:
 motd:
  permission: motd.commands
  description: server's name edit plugin
  usage: "/motd"
  default: OP
  
permissions:
 motd.commands:
  default: OP
